In [19]:
from scipy import stats
import numpy as np
x = [1,2,3,4,5]
y = [1,2,3,4,5]
slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)
print('slope:', slope, 'intercept:', intercept, 'r_value:', r_value, 'p_value:', p_value, 'std_err:', std_err)

slope: 1.0 intercept: 0.0 r_value: 1.0 p_value: 1.2004217548761408e-30 std_err: 0.0


In [23]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

def func(x, a, b, c):
    return a * np.exp(-b * x) + c

x = np.linspace(0,4,50)
y = func(x, 2.5, 1.3, 0.5)
yn = y + 0.2*np.random.normal(size=len(x))

popt, pcov = curve_fit(func, x, yn)
print(popt)

[2.46373016 1.45417268 0.52843872]


In [24]:
print(pcov)

[[ 0.01694505  0.00842083 -0.00066516]
 [ 0.00842083  0.02498429  0.00548533]
 [-0.00066516  0.00548533  0.00253933]]
